export const routes = {
  home: "/",
  markets: "/markets",
  topTraders: "/top-traders",
  howItWorks: "/how-it-works",
  pricing: "/pricing",
  security: "/security",
  faq: "/faq",
  login: "/login",
  register: "/register",
  dashboard: "/dashboard",
  terminal: "/terminal",
  copyTrading: "/copy-trading",
  traderMarketplace: "/trader-marketplace",
  wallet: "/wallet",
  history: "/history",
  verification: "/verification",
  support: "/support",
  settings: "/settings",
  admin: "/admin",
  adminUsers: "/admin/users",
  adminTradingPairs: "/admin/trading-pairs",
  adminDeposits: "/admin/deposits",
  adminWithdrawals: "/admin/withdrawals",
  adminBonuses: "/admin/bonuses",
  adminTrades: "/admin/trades",
  adminCopyTrading: "/admin/copy-trading",
  adminReferrals: "/admin/referrals",
  adminSupport: "/admin/support",
  adminSettings: "/admin/settings",
} as const;

export const publicNavItems = [
  { label: "Markets", href: routes.markets },
  { label: "Top Traders", href: routes.topTraders },
  { label: "How it works", href: routes.howItWorks },
  { label: "Pricing", href: routes.pricing },
  { label: "Security", href: routes.security },
  { label: "FAQ", href: routes.faq },
] as const;

export const dashboardNavItems = [
  { label: "Overview", href: routes.dashboard, symbol: "OV" },
  { label: "Terminal", href: routes.terminal, symbol: "TX" },
  { label: "Copy Trading", href: routes.copyTrading, symbol: "CP" },
  { label: "Marketplace", href: routes.traderMarketplace, symbol: "MP" },
  { label: "Wallet", href: routes.wallet, symbol: "WL" },
  { label: "History", href: routes.history, symbol: "HS" },
  { label: "Verification", href: routes.verification, symbol: "KY" },
  { label: "Support", href: routes.support, symbol: "SP" },
  { label: "Settings", href: routes.settings, symbol: "ST" },
] as const;

export const adminNavItems = [
  { label: "Admin Overview", href: routes.admin, symbol: "AO" },
  { label: "Users", href: routes.adminUsers, symbol: "US" },
  { label: "Trading Pairs", href: routes.adminTradingPairs, symbol: "TP" },
  { label: "Deposits", href: routes.adminDeposits, symbol: "DP" },
  { label: "Withdrawals", href: routes.adminWithdrawals, symbol: "WD" },
  { label: "Bonuses", href: routes.adminBonuses, symbol: "BN" },
  { label: "Trades", href: routes.adminTrades, symbol: "TR" },
  { label: "Copy Trading", href: routes.adminCopyTrading, symbol: "CT" },
  { label: "Referrals", href: routes.adminReferrals, symbol: "RF" },
  { label: "Support", href: routes.adminSupport, symbol: "SP" },
  { label: "Settings", href: routes.adminSettings, symbol: "ST" },
] as const;
